{
  entries(
    first: 1
    filter: {
      entryTypeCode: "service"
      taxonsSlug: [
        { taxonomyCode: "service_category", slug: { eq: "service-category-1" } }
      ]
    }
    orderBy: [{ field: "title", direction: ASC }]
  ) {
    count
    edges {
      node {
        slug
        title
        featured
        booleanValues {
          value
        }
        integerValues {
          value
        }
        decimalValues {
          value
        }
        jsonValues {
          value
        }
        selectValues {
          code
          displayName
        }
        images {
          id
          caption
        }
        seo {
          title
          description
          keywords
        }
      }
    }
  }
}
