mutation {
  createSubscriber(
    input: {
      data: {
        formId: 1
        email: "joehua87@gmail.com"
        name: "Joe"
        phone: "0981222111"
        data: "{\"address\":\"111\"}"
      }
    }
  ) {
    result {
      node {
        email
        name
        data
      }
    }
  }
}
