{
  entries(
    first: 5
    filter: {
      taxonsPath: [
        { taxonomyCode: "product_category", path: { match: "*.8.*" } }
        { taxonomyCode: "product_category", path: { match: "*.8.*" } }
      ]
    }
  ) {
    count
    edges {
      node {
        id
        slug
        title
        taxons {
          id
          _id
          slug
          path
          taxonomy {
            code
          }
        }
      }
    }
  }
}
