mutation {
  editEntry(
    input: {
      id: "RW50cnk6Mg=="
      data: { title: "Edited title", slug: "edited-title" }
    }
  ) {
    result {
      node {
        slug
        title
      }
    }
  }
}
