{
  entries(
    first: 10
    orderBy: [
      { field: "price", fieldType: DECIMAL, direction: DESC_NULLS_LAST }
      { field: "id", direction: ASC }
    ]
  ) {
    count
    edges {
      node {
        slug
        title
        decimalValues {
          fieldId
          value
        }
      }
    }
  }
}
