{
  taxons(
    first: 3
    filter: { taxonomyCode: "service_category" }
    orderBy: [{ field: "title", direction: ASC }]
  ) {
    count
    edges {
      node {
        slug
        title
        featured
      }
    }
  }
}
