{
  entries(
    first: 10
    filter: {
      entryTypeCode: "service"
      taxonsPath: [
        { taxonomyCode: "service_category", path: { match: "3.*" } }
        { taxonomyCode: "service_category", path: { match: "4" } }
      ]
    }
  ) {
    count
    edges {
      node {
        slug
        title
        featured
      }
    }
  }
}
