{
  fields(
    first: 2
    offset: 2
    orderBy: [{ field: "position", direction: DESC }]
  ) {
    count
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        code
        displayName
        position
      }
    }
  }
}
